19/11/25 21:26:07 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
19/11/25 21:26:07 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
19/11/25 21:26:07 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
19/11/25 21:26:07 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
19/11/25 21:26:07 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
19/11/25 21:26:07 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
19/11/25 21:26:07 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
19/11/25 21:26:07 WARN Utils: Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
19/11/25 21:26:07 WARN Utils: Service 'SparkUI' could not bind on port 4048. Attempting port 4049.
19/11/25 21:26:07 WARN Utils: Service 'SparkUI' could not bind on port 4049. Attempting port 4050.
19/11/25 21:26:07 WARN Utils: Service 'SparkUI' could not bind on port 4050. Attempting port 4051.
19/11/25 21:26:07 WARN Utils: Service 'SparkUI' could not bind on port 4051. Attempting port 4052.
19/11/25 21:26:07 WARN Utils: Service 'SparkUI' could not bind on port 4052. Attempting port 4053.
19/11/25 21:26:07 WARN Utils: Service 'SparkUI' could not bind on port 4053. Attempting port 4054.
19/11/25 21:26:07 WARN Utils: Service 'SparkUI' could not bind on port 4054. Attempting port 4055.
19/11/25 21:26:08 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
Traceback (most recent call last):
  File "/share/apps/spark/spark-2.4.0-bin-hadoop2.6/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/share/apps/spark/spark-2.4.0-bin-hadoop2.6/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o52.load.
: org.apache.spark.sql.AnalysisException: Path does not exist: hdfs://dumbo/user/hw1964/'/user/hm74/NYCOpenData/2232-dj5q.tsv.gz';
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:558)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:545)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:355)
	at org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:545)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:359)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hw1964/final/task1/test.py", line 201, in <module>
    .load(sys.argv[1])
  File "/share/apps/spark/spark-2.4.0-bin-hadoop2.6/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 166, in load
  File "/share/apps/spark/spark-2.4.0-bin-hadoop2.6/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/share/apps/spark/spark-2.4.0-bin-hadoop2.6/python/lib/pyspark.zip/pyspark/sql/utils.py", line 69, in deco
pyspark.sql.utils.AnalysisException: "Path does not exist: hdfs://dumbo/user/hw1964/'/user/hm74/NYCOpenData/2232-dj5q.tsv.gz';"
19/11/25 21:26:24 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
19/11/25 21:26:24 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
19/11/25 21:26:24 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
19/11/25 21:26:24 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
19/11/25 21:26:24 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
19/11/25 21:26:24 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
19/11/25 21:26:24 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
19/11/25 21:26:24 WARN Utils: Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
19/11/25 21:26:24 WARN Utils: Service 'SparkUI' could not bind on port 4048. Attempting port 4049.
19/11/25 21:26:24 WARN Utils: Service 'SparkUI' could not bind on port 4049. Attempting port 4050.
19/11/25 21:26:24 WARN Utils: Service 'SparkUI' could not bind on port 4050. Attempting port 4051.
19/11/25 21:26:24 WARN Utils: Service 'SparkUI' could not bind on port 4051. Attempting port 4052.
19/11/25 21:26:24 WARN Utils: Service 'SparkUI' could not bind on port 4052. Attempting port 4053.
19/11/25 21:26:24 WARN Utils: Service 'SparkUI' could not bind on port 4053. Attempting port 4054.
19/11/25 21:26:24 WARN Utils: Service 'SparkUI' could not bind on port 4054. Attempting port 4055.
19/11/25 21:26:25 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
Traceback (most recent call last):
  File "/share/apps/spark/spark-2.4.0-bin-hadoop2.6/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/share/apps/spark/spark-2.4.0-bin-hadoop2.6/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o52.load.
: org.apache.spark.sql.AnalysisException: Path does not exist: hdfs://dumbo/user/hw1964/'/user/hm74/NYCOpenData/22rr-ujq3.tsv.gz';
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:558)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:545)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:355)
	at org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:545)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:359)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hw1964/final/task1/test.py", line 201, in <module>
    .load(sys.argv[1])
  File "/share/apps/spark/spark-2.4.0-bin-hadoop2.6/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 166, in load
  File "/share/apps/spark/spark-2.4.0-bin-hadoop2.6/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/share/apps/spark/spark-2.4.0-bin-hadoop2.6/python/lib/pyspark.zip/pyspark/sql/utils.py", line 69, in deco
pyspark.sql.utils.AnalysisException: "Path does not exist: hdfs://dumbo/user/hw1964/'/user/hm74/NYCOpenData/22rr-ujq3.tsv.gz';"
19/11/25 21:26:42 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
19/11/25 21:26:42 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
19/11/25 21:26:42 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
19/11/25 21:26:42 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
19/11/25 21:26:42 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
19/11/25 21:26:42 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
19/11/25 21:26:42 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
19/11/25 21:26:42 WARN Utils: Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
19/11/25 21:26:42 WARN Utils: Service 'SparkUI' could not bind on port 4048. Attempting port 4049.
19/11/25 21:26:42 WARN Utils: Service 'SparkUI' could not bind on port 4049. Attempting port 4050.
19/11/25 21:26:42 WARN Utils: Service 'SparkUI' could not bind on port 4050. Attempting port 4051.
19/11/25 21:26:42 WARN Utils: Service 'SparkUI' could not bind on port 4051. Attempting port 4052.
19/11/25 21:26:42 WARN Utils: Service 'SparkUI' could not bind on port 4052. Attempting port 4053.
19/11/25 21:26:42 WARN Utils: Service 'SparkUI' could not bind on port 4053. Attempting port 4054.
19/11/25 21:26:42 WARN Utils: Service 'SparkUI' could not bind on port 4054. Attempting port 4055.
19/11/25 21:26:43 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
